### ISSUE TITLE
Unclear unit and direction of latitude and longitude

### ISSUE THREAD

**Issue by d70-t** [orcestra-campaign/sattracks#1]
Currently the files include columns marked as follows:

```
SUBLAT[W+]    SUBLON[N+] 
```

this suggests that the file would include a latitude counting west positive, but usually latitudes are counted in north-south direction. So likely the column names and units have been mixed.

**Comment by florian-ewald** [comment]
Yes, you are right - the header should read like:
   GMT      SUBLAT[**N+**]    SUBLON[**W+**]  HEADING

I will correct that with the new orbit forcasts. The positive westward longitudes where chosen to be compliant with the MSS format which stems from: https://cloudsgate2.larc.nasa.gov/cgi-bin/predict/predict.cgi
