### ISSUE TITLE
sat tracks hard wired to cape verde

### ISSUE THREAD

**Issue by bjorn-stevens** [orcestra-campaign/sattracks#2]
As best I can tell the satellite data is organized by region of interest (ROI), but the building of url's hardcodes this to one region of interest, namely cape verde.  

I had to hack it to get to the barbados orbits, but it would be nice if this were more flexible in case others want to already plan a bit ahead.

**Comment by d70-t** [comment]
There's now (since ae90f91d9b52d2203acbd48af4a6c9e8282d76af) a new index format (`index_v2.csv`) which does support multiple ROIs.
